Repository redis-developer/redis-developer.github.io, pull requests merged in 2021-11, with the labels that each got.

#154 Adds author to crash course.
  docs/develop/node/node-crash-course/advancedstreams/index-advancedstreams.mdx
  docs/develop/node/node-crash-course/caching/index-caching.mdx
  docs/develop/node/node-crash-course/checkinswithstreams/index-checkinswithstreams.mdx
  docs/develop/node/node-crash-course/coursewrapup/index-coursewrapup.mdx
  docs/develop/node/node-crash-course/domainobjectswithhashes/index-domainobjectswithhashes.mdx
  docs/develop/node/node-crash-course/index-node-crash-course.mdx
  docs/develop/node/node-crash-course/introducingredisinsight/index-introducingredisinsight.mdx
  docs/develop/node/node-crash-course/introductiontomodules/index-introductiontomodules.mdx
  docs/develop/node/node-crash-course/managingsuccess/index-managingsuccess.mdx
  docs/develop/node/node-crash-course/redisandnodejs/index-redisandnodejs.mdx
  docs/develop/node/node-crash-course/redisbloom/index-redisbloom.mdx
  docs/develop/node/node-crash-course/redisearch/index-redisearch.mdx
  docs/develop/node/node-crash-course/redisjson/index-redisjson.mdx
  docs/develop/node/node-crash-course/runningtheapplication/index-runningtheapplication.mdx
  docs/develop/node/node-crash-course/sampleapplicationoverview/index-sampleapplicationoverview.mdx
  docs/develop/node/node-crash-course/sessionstorage/index-sessionstorage.mdx
  docs/develop/node/node-crash-course/welcome/index-welcome.mdx
  docs/develop/node/node-crash-course/whatisredis/index-whatisredis.mdx
Labels: documentation

#156 Removed announcement bar now Hacktoberfest is over.
  docusaurus.config.js
Labels: content

#155 Removed console log I left in by accident.
  src/theme/DocItem/index.tsx
Labels: bug

#134 Makes the next/prev links configurable, defaults to on.
  docs/get-involved/hacktoberfest/index-hacktoberfest.mdx
  src/theme/DocItem/index.tsx
Labels: enhancement

#133 Make the "Edit this page" link configurable (on/off)
  docs/get-involved/hacktoberfest/index-hacktoberfest.mdx
  src/theme/DocItem/index.tsx
Labels: enhancement

#170 Add Getting Started with Redis OM Python tutorial
  docs/develop/python/fastapi/index-fastapi.mdx
  docs/develop/python/redis-om/index-redis-om.mdx
  docusaurus.config.js
  static/img/profile_pic_andrew_brookins.jpg
Labels: documentation, enhancement

#185 Update RedisJSON for Node.js howto for Node Redis 4
  docs/howtos/redisjson/getting-started/index-gettingstarted.mdx
  docs/howtos/redisjson/json-using-redisearch/jsonindex-document/index-jsonindex-document.mdx
  docs/howtos/redisjson/jsonind-document/index-jsonind-document.mdx
  docs/howtos/redisjson/storing-complex-json-document/index-storing-complex-json-document.mdx
  docs/howtos/redisjson/storing-json-using-nodejs/index-storingjson-nodejs.mdx
  docs/howtos/redisjson/using-go/index-usinggo.mdx
  docs/howtos/redisjson/using-java/index-usingjava.mdx
  docs/howtos/redisjson/using-nodejs/index-usingnodejs.mdx
  docs/howtos/redisjson/using-python/index-usingpython.mdx
  docs/howtos/redisjson/using-redisinsight/index-usingredisinsight.mdx
  docs/howtos/redisjson/using-ruby/index-usingruby.mdx
Labels: documentation

#190 Adds Devcember project page.
  docs/get-involved/devcember/index-devcember.mdx
  sidebars.js
Labels: documentation, enhancement

#181 Python + RedisJSON
  docs/howtos/redisjson/using-python/index-usingpython.mdx
Labels: documentation
